// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-xLCKCQEbUcV1e6pGDoMINRMtNKln3fs',
    appId: '1:341771521038:web:0c6e74523a93610ba0405f',
    messagingSenderId: '341771521038',
    projectId: 'marketcoach-db8f4',
    authDomain: 'marketcoach-db8f4.firebaseapp.com',
    storageBucket: 'marketcoach-db8f4.firebasestorage.app',
    measurementId: 'G-FQC9LHLXXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8WqVpg7K13o1t4_6j5IP6vn0i6Gc2-oc',
    appId: '1:341771521038:android:614d1f35f2918b92a0405f',
    messagingSenderId: '341771521038',
    projectId: 'marketcoach-db8f4',
    storageBucket: 'marketcoach-db8f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc_idWd_mW-RQBMFxScAqHWftyOu0ig9E',
    appId: '1:341771521038:ios:cd0151b7b952f1c9a0405f',
    messagingSenderId: '341771521038',
    projectId: 'marketcoach-db8f4',
    storageBucket: 'marketcoach-db8f4.firebasestorage.app',
    androidClientId: '341771521038-l7jig4lo8mnqlu7p1ibrbv107dbr58bm.apps.googleusercontent.com',
    iosClientId: '341771521038-rso5cpefh8rtuq1p602ajhg87hbunsdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.marketCoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc_idWd_mW-RQBMFxScAqHWftyOu0ig9E',
    appId: '1:341771521038:ios:cd0151b7b952f1c9a0405f',
    messagingSenderId: '341771521038',
    projectId: 'marketcoach-db8f4',
    storageBucket: 'marketcoach-db8f4.firebasestorage.app',
    androidClientId: '341771521038-l7jig4lo8mnqlu7p1ibrbv107dbr58bm.apps.googleusercontent.com',
    iosClientId: '341771521038-rso5cpefh8rtuq1p602ajhg87hbunsdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.marketCoach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-xLCKCQEbUcV1e6pGDoMINRMtNKln3fs',
    appId: '1:341771521038:web:9cd3b475f85ac603a0405f',
    messagingSenderId: '341771521038',
    projectId: 'marketcoach-db8f4',
    authDomain: 'marketcoach-db8f4.firebaseapp.com',
    storageBucket: 'marketcoach-db8f4.firebasestorage.app',
    measurementId: 'G-3F5Z9JV5FJ',
  );
}
